# Generated by Django 5.1.3 on 2024-11-09 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web1', '0002_pizza_user_alter_pizza_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='pizza',
            name='preview',
            field=models.ImageField(default=13, upload_to=''),
            preserve_default=False,
        ),
    ]
